version: "3"

services:
  app:
    image: registry.git.ee.ethz.ch/pbl/research/armasuisse/armasuisse-2023/metavisionsdk_docker/metavision22:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    ulimits:
      nofile:
        soft: "1024"
        hard: "65536"
