version: "3"

services:
  app:
    image: metavision
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
