version: "3"

services:
  app:
    image: metavision22_${USER}:latest
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    ulimits:
      nofile:
        soft: "1024"
        hard: "65536"
