version: "3.2"

services:
  base:
    image: registry.git.ee.ethz.ch/pbl/research/event-camera/docker/metavisionsdk-docker/metavisionsdk22:latest
    build: 
      context: .
      dockerfile: Dockerfile_base
    profiles:
      - base_image

  metavisionsdk:
    image: metavisionsdk22_${USER}:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME=${USER}
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - PASSWORD=${PASSWORD}
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    privileged: true
    ulimits:
      nofile:
        soft: "1024"
        hard: "65536"